-- Pièces détachées : le stock de pièces de rechange conservées à la
-- ludothèque (issu du classeur « pièces détachées.xlsx » tenu par l'équipe).
--
-- À ne pas confondre avec `pieces_trouvees` (pièces orphelines ramassées en
-- attendant de retrouver leur jeu) : ici ce sont des pièces en surplus, rangées
-- par jeu, dans lesquelles on peut piocher quand un exemplaire est incomplet.
--
-- Une ligne par type de pièce et par jeu, la quantité étant écrite dans la
-- description telle qu'elle figure dans le classeur (« 19 grosses billes noires »).

CREATE TABLE IF NOT EXISTS pieces_detachees (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  nom_jeu     TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_pieces_detachees_nom_jeu ON pieces_detachees (nom_jeu);

INSERT INTO pieces_detachees (nom_jeu, description) VALUES
  ('Carcassonne Junior', '35 tuiles'),
  ('Abalone', '19 grosses billes noires'),
  ('Abalone', '18 grosses billes blanches'),
  ('Awale', '17 petits cylindres en bois'),
  ('Awale', '1 petit cylindre transparent et violet'),
  ('Abyss', '1 bloc-notes'),
  ('Azul', '1 carré bleu'),
  ('Azul', '1 carré rouge'),
  ('Azul', '1 carré noir avec symbole bleu'),
  ('A dos de chameau', '3 chameaux rouges'),
  ('A dos de chameau', '3 chameaux jaunes'),
  ('A dos de chameau', '3 chameaux oranges'),
  ('A dos de chameau', '1 chameau marron'),
  ('A dos de chameau', '47 cartes chameaux (de différentes couleurs)'),
  ('croa', '6 petites grenouilles bleues'),
  ('croa', '6 petites grenouilles roses'),
  ('croa', '5 petites grenouilles vertes'),
  ('croa', '6 petites grenouilles rouges'),
  ('croa', '4 grosses grenouilles (rose bleue rouge verte)'),
  ('croa', '18 jetons grenouilles (couleurs différentes)'),
  ('croa', '63 tuiles'),
  ('chicky boom', '1 gros jeton rouge avec chiffre 1 jaune'),
  ('Concept kids', '1 carré orange'),
  ('Concept kids', '1 support avec des pattes d''animaux'),
  ('Concept kids', '43 cartes animaux rouge'),
  ('Concept kids', '45 cartes animaux bleus'),
  ('Concept', '2 pions point d''interrogation'),
  ('Concept', '7 pions point d''exclamation (2 noirs 2 rouges 2 jaunes 1 bleu)'),
  ('Concept', '47 jetons une ampoule'),
  ('Concept', '22 jetons deux ampoules'),
  ('Catan à l''aube de l''humanité', '2 pions de 2 personnages'),
  ('Croque carotte', '47 cartes (carotte et avancer de 1 à 3 cases)'),
  ('Croque carotte', '2 pions lapins violets'),
  ('Croque carotte', '4 pions lapins roses'),
  ('Croque carotte', '2 pions lapins bleus'),
  ('Carcassonne', '3 tuiles blanches'),
  ('Carapate', '1 jeton salade'),
  ('La tour enchantée', '2 clés'),
  ('La tour enchantée', '2 pions (rouge et bleu)'),
  ('La tour enchantée', '2 dés différents'),
  ('La tour enchantée', '16 jetons ronds'),
  ('Catan junior', '3 pions bateaux pirates (bleu jaune rouge)'),
  ('Catan junior', '1 pion violet batiment'),
  ('Clefs magiques', '4 pierres rouges'),
  ('Citadelle', '1 carte explication des personnages'),
  ('Celestia', '1 carte bleue'),
  ('Celestia', '8 pièces carton (morceaux de construction en bois)'),
  ('Coloretto', '41 cartes caméléons (différentes couleurs)'),
  ('cubosaurs', '1 jeton adn'),
  ('Cluedo', '1 corde'),
  ('Cluedo', '1 pion violet'),
  ('Cluedo', '6 pièces en metal'),
  ('Catane', '4 chemins en plastique (blancx2 jaune rouge)'),
  ('Hokito', '1 jeton rond symbole marron et doré'),
  ('Happy chicken', '4 poussins jaunes'),
  ('Happy chicken', '1 poussin noir'),
  ('Happy chicken', '12 jetons ronds de couleur (vert bleu rouge jaune)'),
  ('Happy chicken', '4 jetons ronds poulet'),
  ('Huns', '1 bloc-notes'),
  ('Happy city', '1 petite carte cabane'),
  ('El captain', '1 jeton rond pièce symbole'),
  ('Expedition', '1 flèche jaune en plastique'),
  ('Everdell', '1 cylindre marron'),
  ('Les Eclairtout', '1 rond en plastique noir'),
  ('Extinction', '7 jetons liasses de billets'),
  ('Augustus', '1 bloc-notes (abimé)'),
  ('Codenames', '3 cartes vierges'),
  ('Game over deluxe', '3 grosses tuiles blanches'),
  ('La chasse aux gigamon', '6 jetons marrons'),
  ('Grouille grenouille', '1 jeton petite blanche en bois'),
  ('Gardien des saisons', '1 jeton rond flocon'),
  ('Ghost adventure', '6 petits batons blancs en plastique'),
  ('Find the code', '1 cadenas (+ le code)'),
  ('Fourmidable', '12 ronds en plastiques (différentes couleurs)'),
  ('Fourmidable', '1 jeton rond marron'),
  ('Fourmidable', '31 jetons jaune et bleu'),
  ('Get On Board', '1 bloc-notes'),
  ('Downforce', '1 bloc-notes'),
  ('duplik', '1 bloc-notes'),
  ('Decrypto', '1 bloc-notes'),
  ('13 indices', '1 bloc-notes'),
  ('7 wonders duel', '2 bloc-notes'),
  ('Dorf Romantik', '11 tuiles vertes'),
  ('Dorf Romantik', '18 jetons appareil photo'),
  ('Dorf Romantik', '1 jeton photographe avec son socle'),
  ('Dorf Romantik', '9 jetons avec chiffres (couleurs et symboles différents)'),
  ('Docteur panic', '9 charlottes'),
  ('Dr Eureka', '3 billes (violet rouge vert)'),
  ('Dominion', '7 cartes vierges'),
  ('Dixit', '6 gros lapins en bois (différentes couleurs)'),
  ('Dixit', '6 petits lapins en bois (différentes couleurs)'),
  ('Dixit', '8 marqueurs rouges en plastique'),
  ('Dice Throne', '1 jeton goutte'),
  ('Decrocher la lune', '4 échelles'),
  ('Dali le renard', '6 jetons œufs ronds en plastique'),
  ('Ice cool', '1 jeton poisson en bois'),
  ('Imagine', '34 cartes transparentes'),
  ('Blokus', '13 formes'),
  ('Boufbowl', '2 jetons'),
  ('Biomos', '9 jetons'),
  ('Boum', '4 jetons terre'),
  ('Boum', '2 jetons pierre (jaune et orange)'),
  ('Break the code', '1 bloc-notes'),
  ('Bang', '2 cartes (bière et bang)'),
  ('Bang', '5 jetons balles'),
  ('Bang', '3 jetons balles triple'),
  ('Bang', '2 jetons flèche'),
  ('Big Pirate', '1 pion pirate'),
  ('Après l''orage', '1 fiche de règles'),
  ('Danger dice dungeon', '1 bloc-notes'),
  ('Kaleidoscope junior', '3 jetons en plastiques (violet jaune vert)'),
  ('Corinth', '1 bloc-notes'),
  ('Codenames duo', '1 bloc-notes'),
  ('cartographer', '1 bloc-notes'),
  ('Boreal', '1 pièce de plateau'),
  ('Kahuna', '14 cartes'),
  ('Kahuna', '28 batons en bois blanc'),
  ('Kahuna', '8 ronds en bois blanc'),
  ('Kahuna', '25 batons en bois noir'),
  ('Kahuna', '10 ronds en bois noir'),
  ('Kamisado', '1 tour marbre blanc noir'),
  ('Kamisado', '1 cylindre transparent en plastique'),
  ('Karuba', '4 pépites d''or'),
  ('Karuba', '3 petits diamants'),
  ('Kluster', '7 pièces aimantées'),
  ('Kosmopolit', '1 bloc-notes (2 fiches)'),
  ('Kaleidos', '1 bloc-notes'),
  ('Kingdomin', '4 pièces de château'),
  ('Le jeu du loup', '16 gros jetons ronds (verts et 2 jaunes)'),
  ('Le jeu du loup', '1 sac en tissu'),
  ('Le jeu du loup', '30 jetons faune et flore (6 éléments différents)'),
  ('Le jeu du loup', '6 magnets vêtements'),
  ('Le jeu du loup', '4 plateaux feuilles'),
  ('Les aventuriers du rail junior', '6 trains verts'),
  ('Les aventuriers du rail junior', '6 trains bleus'),
  ('Les aventuriers du rail junior', '5 trains rouges'),
  ('Les aventuriers du rail junior', '6 trains jaunes'),
  ('Lacuna', '14 fleurs en bois (divisé en 7 couleurs)'),
  ('La bonne paye', '2 cartes prêt'),
  ('Les aventuriers du rail', '9 trains bleus'),
  ('Les aventuriers du rail', '9 trains noirs'),
  ('Les aventuriers du rail', '9 trains jaunes'),
  ('Les aventuriers du rail', '8 trains verts'),
  ('Les aventuriers du rail', '9 trains rouges'),
  ('Les aventuriers du rail monde', '15 bateaux (divisé en 4 couleurs)'),
  ('Les aventuriers du rail monde', '17 trains (divisé en 4 couleurs +2 noirs)'),
  ('Les aventuriers du rail scandinavie', '5 trains blancs'),
  ('Les aventuriers du rail scandinavie', '6 trains noirs'),
  ('Les aventuriers du rail scandinavie', '5 trains violets'),
  ('Le clan des souris', '1 jeton rond pleine lune'),
  ('Le verger', '3 pièces en bois'),
  ('Le lynx', '5 jetons ronds colorés (vert orange jaune)'),
  ('Le lynx', '6 tuiles (5 lynx)'),
  ('Le hérisson qui roule à pique', '7 jetons à scratch (pomme champi feuille visage)'),
  ('Labyrinthe magique', '1 jeton bleu'),
  ('Les aventuriers du rail France', '5 trains blancs'),
  ('Les ruines perdues de Nanak', '2 jetons parchemins'),
  ('Les ruines perdues de Nanak', '3 pierres (rouge et bleue)'),
  ('La tour du dragon', '1 jeton pion personnage (en 2 parties)'),
  ('Les aventuriers du rail Amsterdam', '4 wagons'),
  ('L''île interdite', '5 marqueurs'),
  ('One Key', '5 jetons ronds clés'),
  ('Outlaws Last Man Standing', '1 fiche nouveaux personnages'),
  ('Outlaws Last Man Standing', '18 cartes personnages'),
  ('Le petit prince', '55 cartes'),
  ('Le petit prince', '9 tuiles avion'),
  ('Le petit prince', '6 jetons étoiles'),
  ('Le petit prince', '5 jetons téléscope'),
  ('Le petit prince', '4 jetons avion en papier'),
  ('Le petit prince', '1 pièce de plateau'),
  ('Maître renard', '4 masques'),
  ('Maître renard', '8 grandes cartes'),
  ('Maître renard', '12 jetons œufs'),
  ('Maître renard', '18 jetons œufs triple'),
  ('Monopoly', '60 billets de 100'),
  ('Monopoly', '90 billets de 500 +1 orange'),
  ('Monopoly', '125 billets de 1000'),
  ('Monopoly', '37 billets de 2000'),
  ('Monopoly', '45 billets de 5000'),
  ('Monopoly', '78 billets de 10000'),
  ('Monopoly', '13 billets de 50000'),
  ('Monopoly', '94 bâtiments maisons'),
  ('Monopoly', '1 billet de 1'),
  ('Le rallye des vers de terre', '1 cylindre'),
  ('Mosquito show', '8 jetons verts moustiques'),
  ('Mosquito show', '1 pion perroquet'),
  ('Micro macro', '16 pochettes scénario'),
  ('Mycelia', '5 petits jetons ronds bleus'),
  ('Mycelia', '8 petits jetons ronds violets'),
  ('Mysterium', '4 grandes cartes'),
  ('Mysterium', '2 cartes suspect ''2'' et ''13'''),
  ('Mysterium', '2 cartes lieu ''24'' et ''32'''),
  ('Mysterium', '2 cartes arme ''39'' et 43'''),
  ('Mange qui peut', '4 cartes'),
  ('Morris le dodo', '1 jeton œuf'),
  ('Medieval academy', '4 jetons bouclier'),
  ('Marrakesh', '1 pièce de 1'),
  ('Marrakesh', '3 pièces de 5'),
  ('Miniville', '5 pièces de 1'),
  ('Miniville', '3 pièces de 5'),
  ('Miniville', '3 pièces de 10'),
  ('Kronologic', '1 bloc-notes'),
  ('Kyudo', '1 bloc-notes (détaché)'),
  ('Jurrassic branch', '4 gros jetons (jaune vert)'),
  ('Jamaica', '9 petites cartes'),
  ('Jamaica', '42 cartes (différents personnages)'),
  ('Jamaica', '5 plateaux (planches)'),
  ('Jamaica', '59 jetons pièces d''or'),
  ('Jamaica', '39 jetons nourriture'),
  ('Jamaica', '36 jetons canon'),
  ('Jamaica', '4 jetons coffre'),
  ('Jungle speed', '1 totem'),
  ('Just one', '7 présentoirs blancs en plastique'),
  ('Loony quest', '18 planches monde'),
  ('Loony quest', '18 planches transparentes'),
  ('Loony quest', '3 planches'),
  ('Yumyum', '2 petits ronds roses'),
  ('Zombies kids', '1 enveloppe'),
  ('Strike', '1 règle du jeu'),
  ('Strike', '28 dés'),
  ('Wazabi', '1 sac en tissu'),
  ('Wazabi', '20 dés'),
  ('Welcome', '1 bloc-notes'),
  ('SOS ouistiti', '26 batons en plastiques'),
  ('SOS ouistiti', '1 dé'),
  ('SOS ouistiti', '31 singes'),
  ('Shadow hunter', '14 cartes personnage (rôles et couleurs)'),
  ('Shadow hunter', '6 cartes lieu'),
  ('Shadow hunter', '16 cartes lumière'),
  ('Shadow hunter', '16 cartes vision'),
  ('Sol', '13 petits jetons'),
  ('Sol', '1 jeton'),
  ('sheep hop', '2 tuiles'),
  ('Triominos', '1 jeton 1'),
  ('Silk', '1 tuile +5'),
  ('sos dino', '4 pions dinosaures'),
  ('sos dino', '6 petits jetons œufs'),
  ('sos dino', '4 socles blancs'),
  ('sos dino', '62 tuiles'),
  ('sos dino', '18 rochers en plusieurs parties'),
  ('slide quest', '1 indicateur de niveau et de vie'),
  ('slide quest', '4 barrières'),
  ('slide quest', '4 arches'),
  ('slide quest', '3 pions verts'),
  ('slide quest', '2 cylindres rouges'),
  ('Skyjo', '1 bloc-notes'),
  ('Spellcaster', '1 règle du jeu'),
  ('Sherlock 13', '1 bloc-notes'),
  ('sauve moutons', '10 moutons'),
  ('sauve moutons', '1 chien loup'),
  ('sauve moutons', '1 maison'),
  ('sauve moutons', '1 meeple'),
  ('sauve moutons', '2 tuiles'),
  ('sauve moutons', '24 cartes'),
  ('So clover', '2 plateaux trèfles en plastique'),
  ('Risk junior', '2 dés'),
  ('Risk junior', '12 petites cartes trésor'),
  ('Risk junior', '3 bateaux (bleu vert rouge)'),
  ('Risk junior', '32 jetons ronds pirates'),
  ('rock me archimedes', '2 petites billes noires'),
  ('rock me archimedes', '3 petires billes blanches'),
  ('Rafle de chaussette', '1 carte'),
  ('Risk', '14 pions soldats (diiférentes couleurs)'),
  ('Rumble in the house', '1 personnage (et son socle)'),
  ('Rab root', '18 tuiles vierges'),
  ('Rab root', '1 rond blanc'),
  ('Rummikub lettre', '1 lettre A'),
  ('Rollit', '59 billes'),
  ('Quadropolis', '1 bloc-notes'),
  ('quoridor pac-man', '1 pion fantôme'),
  ('Quixo', '5 cubes en bois'),
  ('Portrait robot', '1 fiche'),
  ('Patchwork', '1 jeton bouton'),
  ('Pigeon pigeon', '1 bloc-notes'),
  ('Pylos', '3 billes en bois'),
  ('Plouf party', '1 meeple');
